services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-supersecret}
      POSTGRES_USER: flask_user
      POSTGRES_DB: flask_db
      DB_PORT: 5432
      DB_HOST: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flask_user -d flask_db" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: redis-server --appendonly yes
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build: .
#      context: .
#      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: supersecret
      DB_NAME: api_db
      DEBUG: "false"
      FLASK_APP: app.app
    ports: ["5000:5000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
    internal: true
    name: flask_frontend
  backend:
    driver:  bridge
    internal: true
    name: flask_backend

volumes:
  db-data:
    name: flask_db_data
